# Generated by Django 2.1.1 on 2018-10-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('crisis_id', models.AutoField(primary_key=True, serialize=False)),
                ('crisis_description', models.TextField()),
                ('crisis_assitance', models.CharField(max_length=30)),
                ('crisis_time', models.DateTimeField(auto_now_add=True)),
                ('crisis_location', models.TextField()),
                ('crisis_status', models.CharField(choices=[('PD', 'Pending'), ('DP', 'Dispached'), ('RS', 'Resolved')], default='PD', max_length=254)),
            ],
            options={
                'ordering': ['-crisis_id'],
            },
        ),
        migrations.CreateModel(
            name='CrisisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField()),
                ('operator_password', models.CharField(max_length=20)),
                ('operator_name', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField()),
                ('crisis', models.ManyToManyField(to='api.Crisis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operator_id'],
            },
        ),
        migrations.AddField(
            model_name='crisis',
            name='crisis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CrisisType'),
        ),
    ]
