# Generated by Django 2.1.1 on 2018-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='crisis_type',
        ),
        migrations.AddField(
            model_name='crisis',
            name='crisis_type',
            field=models.ManyToManyField(to='api.CrisisType'),
        ),
    ]
